version: 0.2

phases:
  install:
    commands:
      - cd src
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - sam package --s3-bucket userbucketprueba --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml
