AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.handler
      Runtime: nodejs20.x
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: Users
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Users
